import {
    LOAD_USER_PROFILE_FAIL,
    LOAD_USER_PROFILE_SUCCESS,
    UPDATE_USER_PROFILE_SUCCESS,
    UPDATE_USER_PROFILE_FAIL
    
} from '../actions/types'

const initialState = {

    username:'',
    first_name:'',
    lastt_name:'',
    phone:'',
    college:'',
    status:'',
    city:'',
    linkedin:'',
    email:'',
    about:'',
    we1:'',
    wed1:'',
    wel11:'',
    wep12:'',
    wep13:'',
    wep14:'',
    wep15:'',
    we2:'',
    wed2:'',
    wel21:'',
    wep22:'',
    wep23:'',
    wep24:'',
    wep25:'',
    we3:'',
    wed3:'',
    wel31:'',
    wep32:'',
    wep33:'',
    wep34:'',
    wep35:'',
    class10:'',
    class10marks:'',
    class12:'',
    class12marks:'',
    collegemarks:'',
    skill1:'',
    skill2:'',
    skill3:'',
    skill4:'',
    skill5:'',
    skill6:'',
    skill7:'',
    skill8:'',
    skill9:'',
    skill10:'',
    hna1:'',
    hna2:'',
    hna3:'',
    hna4:'',
    hna5:'',
    lang1:'',
    lang2:'',
    lang3:'',
    lang4:'',
    lang1p:'',
    lang2p:'',
    lang3p:'',
    lang4p:''
};

export default function(state = initialState, action) {
    const {type, payload } = action

    switch(type){
        case LOAD_USER_PROFILE_SUCCESS:
            return {
                ...state,
                username: payload.username,
                first_name: payload.profile.first_name,
                lastt_name: payload.profile.lastt_name,
                phone: payload.profile.phone,
                college: payload.profile.college,
                status:payload.profile.status,
                city:payload.profile.city,
                linkedin:payload.profile.linkedin,
                email:payload.profile.email,
                about:payload.profile.about,
                we1:payload.profile.we1,
                wed1:payload.profile.wed1,
                wel11:payload.profile.wel11,
                wep12:payload.profile.wep12,
                wep13:payload.profile.wep13,
                wep14:payload.profile.wep14,
                wep15:payload.profile.wep15,
                we2:payload.profile.we2,
                wed2:payload.profile.wed2,
                wel21:payload.profile.wel21,
                wep22:payload.profile.wep22,
                wep23:payload.profile.wep23,
                wep24:payload.profile.wep24,
                wep25:payload.profile.wep25,
                we3:payload.profile.we3,
                wed3:payload.profile.wed3,
                wel31:payload.profile.wel31,
                wep32:payload.profile.wep32,
                wep33:payload.profile.wep33,
                wep34:payload.profile.wep34,
                wep35:payload.profile.wep35,
                class10:payload.profile.class10,
                class10marks:payload.profile.class10marks,
                class12:payload.profile.class12,
                class12marks:payload.profile.class12marks,
                collegemarks:payload.profile.collegemarks,
                skill1:payload.profile.skill1,
                skill2:payload.profile.skill2,
                skill3:payload.profile.skill3,
                skill4:payload.profile.skill4,
                skill5:payload.profile.skill5,
                skill6:payload.profile.skill6,
                skill7:payload.profile.skill7,
                skill8:payload.profile.skill8,
                skill9:payload.profile.skill9,
                skill10:payload.profile.skill10,
                hna1:payload.profile.hna1,
                hna2:payload.profile.hna2,
                hna3:payload.profile.hna3,
                hna4:payload.profile.hna4,
                hna5:payload.profile.hna5,
                lang1:payload.profile.lang1,
                lang2:payload.profile.lang2,
                lang3:payload.profile.lang3,
                lang4:payload.profile.lang4,
                lang1p:payload.profile.lang1p,
                lang2p:payload.profile.lang2p,
                lang3p:payload.profile.lang3p,
                lang4p:payload.profile.lang4p
                
            }
            case LOAD_USER_PROFILE_FAIL:
                return {
                    ...state,
                    username:'',
                    first_name:'',
                    lastt_name:'',
                    phone:'',
                    college:'',
                    status:'',
                    city:'',
                    linkedin:'',
                    email:'',
                    about:'',
                    we1:'',
                    wed1:'',
                    wel11:'',
                    wep12:'',
                    wep13:'',
                    wep14:'',
                    wep15:'',
                    we2:'',
                    wed2:'',
                    wel21:'',
                    wep22:'',
                    wep23:'',
                    wep24:'',
                    wep25:'',
                    we3:'',
                    wed3:'',
                    wel31:'',
                    wep32:'',
                    wep33:'',
                    wep34:'',
                    wep35:'',
                    class10:'',
                    class10marks:'',
                    class12:'',
                    class12marks:'',
                    collegemarks:'',
                    skill1:'',
                    skill2:'',
                    skill3:'',
                    skill4:'',
                    skill5:'',
                    skill6:'',
                    skill7:'',
                    skill8:'',
                    skill9:'',
                    skill10:'',
                    hna1:'',
                    hna2:'',
                    hna3:'',
                    hna4:'',
                    hna5:'',
                    lang1:'',
                    lang2:'',
                    lang3:'',
                    lang4:'',
                    lang1p:'',
                    lang2p:'',
                    lang3p:'',
                    lang4p:''
                }
            case UPDATE_USER_PROFILE_SUCCESS:
                return {
                    ...state,
                    username: payload.username,
                    first_name: payload.profile.first_name,
                    lastt_name: payload.profile.lastt_name,
                    phone: payload.profile.phone,
                    college: payload.profile.college,
                    status:payload.profile.status,
                    city:payload.profile.city,
                    linkedin:payload.profile.linkedin,
                    email:payload.profile.email,
                    about:payload.profile.about,
                    we1:payload.profile.we1,
                    wed1:payload.profile.wed1,
                    wel11:payload.profile.wel11,
                    wep12:payload.profile.wep12,
                    wep13:payload.profile.wep13,
                    wep14:payload.profile.wep14,
                    wep15:payload.profile.wep15,
                    we2:payload.profile.we2,
                    wed2:payload.profile.wed2,
                    wel21:payload.profile.wel21,
                    wep22:payload.profile.wep22,
                    wep23:payload.profile.wep23,
                    wep24:payload.profile.wep24,
                    wep25:payload.profile.wep25,
                    we3:payload.profile.we3,
                    wed3:payload.profile.wed3,
                    wel31:payload.profile.wel31,
                    wep32:payload.profile.wep32,
                    wep33:payload.profile.wep33,
                    wep34:payload.profile.wep34,
                    wep35:payload.profile.wep35,
                    class10:payload.profile.class10,
                    class10marks:payload.profile.class10marks,
                    class12:payload.profile.class12,
                    class12marks:payload.profile.class12marks,
                    collegemarks:payload.profile.collegemarks,
                    skill1:payload.profile.skill1,
                    skill2:payload.profile.skill2,
                    skill3:payload.profile.skill3,
                    skill4:payload.profile.skill4,
                    skill5:payload.profile.skill5,
                    skill6:payload.profile.skill6,
                    skill7:payload.profile.skill7,
                    skill8:payload.profile.skill8,
                    skill9:payload.profile.skill9,
                    skill10:payload.profile.skill10,
                    hna1:payload.profile.hna1,
                    hna2:payload.profile.hna2,
                    hna3:payload.profile.hna3,
                    hna4:payload.profile.hna4,
                    hna5:payload.profile.hna5,
                    lang1:payload.profile.lang1,
                    lang2:payload.profile.lang2,
                    lang3:payload.profile.lang3,
                    lang4:payload.profile.lang4,
                    lang1p:payload.profile.lang1p,
                    lang2p:payload.profile.lang2p,
                    lang3p:payload.profile.lang3p,
                    lang4p:payload.profile.lang4p
                }
            case UPDATE_USER_PROFILE_FAIL:
                return{
                    ...state
                }
            
        default:
            return state
    };
};