//auth dipatch states 
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'
export const ALL_USERS = 'ALL_USERS'

//profile dispatch state
export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS'
export const LOAD_USER_PROFILE_FAIL = 'LOAD_USER_PROFILE_FAIL'
export const UPDATE_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAIL = 'LOAD_USER_PROFILE_FAIL'
export const LOAD_USER_ARTICLE_SUCCESS = 'LOAD_USER_ARTICLE_SUCCESS'
export const LOAD_USER_ARTICLE_FAIL = 'LOAD_USER_ARTICLE_FAIL'
export const DELETE_USER_ARTICLE_SUCCESS = 'DELETE_USER_ARTICLE_SUCCESS'
export const DELETE_USER_ARTICLE_FAIL = 'DELETE_USER_ARTICLE_FAIL'
export const ADD_USER_ARTICLE_SUCCESS = 'ADD_USER_ARTICLE_SUCCESS'
export const ADD_USER_ARTICLE_FAIL = 'ADD_USER_ARTICLE_FAIL'
